<?php

namespace App\Models;

use App\Helpers\Functions;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

class Order extends Model
{
    protected $guarded = ['id'];

    public function orderDetails()
    {
        return $this->hasMany(OrderDetail::class, 'order_id', 'id');
    }

    public function customer()
    {
        return $this->belongsTo(Customer::class, 'member_id', 'id');
    }

    public function paymentHistories()
    {
        return $this->hasMany(PaymentHistory::class, 'order_id', 'id');
    }

    public static function search($input)
    {
        $data = self::with( 'orderDetails');

        if ($input) {
            $data = $data
            ->when(isset($input['group']), function ($query) use ($input) {
                $query->whereHas('customer', function ($q) use ($input) {
                    $q->where('group_id', $input['group']);
                });
            })
            ->when(isset($input['telesales']), function ($query) use ($input) {
                $query->whereHas('customer', function ($q) use ($input) {
                   $q->where('telesales_id', $input['telesales']);
                });
            })
            ->when(isset($input['marketing']), function ($query) use ($input) {
                $query->whereHas('customer', function ($q) use ($input) {
                   $q->where('mkt_id', $input['marketing']);
                });
            })
            ->when(isset($input['service']), function ($query) use ($input) {
                $query->whereHas('orderDetails', function ($q) use ($input) {
                   $q->where('booking_id', $input['service']);
                });
            })
            ->when(isset($input['customer']), function ($query) use ($input) {
                $query->whereHas('customer', function ($q) use ($input) {
                   $q->where('full_name', 'like', '%'. $input['customer']. '%')
                   ->orWhere('phone', 'like', '%'. $input['customer']. '%');
                });
            })
            ->when(isset($input['payment_type']), function ($query) use ($input) {
                $query->whereNotNull('payment_type')->where('payment_type', $input['payment_type']);
            })
            ->when(isset($input['data_time']), function ($query) use ($input) {
                $query->when($input['data_time'] == 'TODAY' ||
                    $input['data_time'] == 'YESTERDAY', function ($q) use ($input) {
                    $q->whereDate('created_at', self::getTime(($input['data_time'])));
                })
                ->when($input['data_time'] == 'THIS_WEEK' ||
                    $input['data_time'] == 'LAST_WEEK' ||
                    $input['data_time'] == 'LAST_WEEK' ||
                    $input['data_time'] == 'THIS_MONTH' ||
                    $input['data_time'] == 'LAST_MONTH', function ($q) use ($input) {
                    $q->whereBetween('created_at', self::getTime(($input['data_time'])));
                });
            })
            ->when(isset($input['start_date']) && isset($input['end_date']), function ($q) use ($input) {
                $q->whereBetween('created_at', [Functions::yearMonthDay($input['start_date']), Functions::yearMonthDay($input['end_date'])]);
            });
        }

        return $data->paginate(10);
    }

    public function getNamePaymentTypeAttribute()
    {
        if ($this->payment_type === 1) {
            return "Tiền mặt";
        }

        if ($this->payment_type === 2) {
            return "Thẻ";
        }
    }

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::deleting(function($order) {
            $order->orderDetails()->delete();
        });
    }

    public static function getTime($dataTime)
    {
        $today = Carbon::now('Asia/Ho_Chi_Minh')->format('Y-m-d');

        if ($dataTime == 'TODAY') {
            return $today;
        }

        if ($dataTime == 'YESTERDAY') {
            return Carbon::yesterday()->format('Y-m-d');
        }

        if ($dataTime == 'THIS_WEEK') {
            return [Carbon::now()->startOfWeek()->format('Y-m-d'), Carbon::now()->endOfWeek()->format('Y-m-d')];
        }

        if ($dataTime == 'LAST_WEEK') {
            return ([Carbon::today()->dayOfWeek === 0 ?
                         Carbon::today()->previous(0) :
                         Carbon::today()->previous(0)->previous()->format('Y-m-d'), Carbon::today()->previous(6)->addDay()->format('Y-m-d')]);
        }

        if ($dataTime == 'THIS_MONTH') {
            return ([Carbon::today()->startOfMonth()->format('Y-m-d'),
                     Carbon::tomorrow()->format('Y-m-d')]);
        }

        if ($dataTime == 'LAST_MONTH') {
             return ([Carbon::today()->subMonth()->startOfMonth(), Carbon::today()->subMonth()->endOfMonth()]);
        }
    }
}
